### ISSUE TITLE
Warnings/mechanisms to avoid losing data

### ISSUE THREAD

**Issue by samcooler** [Symphony-DAS/symphony-matlab#22]
At the Schwartz lab, we sometimes make mistakes. One of those mistakes looks like pressing the wrong button, viewing (rather than recording) a bunch of epochs, then realizing they were not recorded at all. In Symphony 1, a large red text indicator made it clear when epochs were not being recorded. In Symphony 2, this is much more subtle, with the only sign being "viewing" rather than "recording" at the bottom.

To ameliorate this issue, it would be good to have some warning, or perhaps a fail-safe mechanism.  Something like the red text, displayed when a data file is open but not being written to, would be a good place to start. Or, perhaps, a confirmation step required for viewing-only when a file is open. Alternatively, all epochs (from both view and record mode) could be saved automatically, then those marked as "view mode" would be not stored with the saved recording h5, unless they were mode-switched beforehand.

**Comment by cafarm** [comment]
What about a popup window that warns the user they're attempting to view with a data file open? Maybe with a checkbox to say "Don't warn me again until the next experiment".

**Comment by samcooler** [comment]
Yes that would be good.
