### ISSUE TITLE
Saving stopped epochs

### ISSUE THREAD

**Issue by samcooler** [Symphony-DAS/symphony-matlab#33]
When a protocol is run, and stopped during an epoch, sometimes the epoch stage display runs through completion. However, the data is dumped and not recorded as an epoch. This means that it is sometimes necessary to wait for an entire extra epoch to run to ensure that the last desired epoch is saved, which is time consuming if epochs are long. Could the stop button be altered to have a "stop after this epoch is completed" functionality?

**Comment by cafarm** [comment]
The pause button is what you're looking for. Pressing pause will pause after the completion of the next epoch. Once paused, you can then press stop if you no longer want to continue.

**Comment by samcooler** [comment]
Okay, thanks Mark.
