### ISSUE TITLE
Record multi clamp series resistance 

### ISSUE THREAD

**Issue by mcafaro** [Symphony-DAS/symphony-matlab#48]
It looks like we missed adding series resistance to the .NET version of the multi clamp data structure.

https://github.com/Symphony-DAS/symphony-core/blob/1ea41a6837e02cc019635a95e836af8964dc2356/src/symphony-core/Symphony.ExternalDevices/MulticlampInterop.cs#L436

We should add it and make sure it is recorded in the data file.

**Comment by cafarm** [comment]
https://github.com/Symphony-DAS/symphony-core/commit/94c691b3ad4f01246fa32f55d24476b856393368
